### ISSUE TITLE
Getting it to work problems

### ISSUE THREAD

**Issue by kronpano** [rnbdev/pysphere#1]
I wanted to try it out but so far no luck

Splitstream can't really be compiled for windows it seems ( https://github.com/rickardp/splitstream/issues/4 and I didn't manage on win10)

Go it all up and running (splitstram and kivy) on a linux laptop - get the control window but it is unusable with a mouse - can't click connect because the moment the mouse moves the drop down list disappears.

Which system did you use to develop on?? 
Is there a version without a UI ? 

Would be a really cool project because the bracketing at the moment is so-so and that might be a way of implementing a better bracketing solution - always depending on what the firmware in the camera accepts.

**Comment by rnbguy** [comment]
Hi. I used Linux to develop this. It does not have any version without UI, but the API functions are inside [misphere.py](https://github.com/rnbdev/pysphere/blob/master/misphere.py).

It has some bugs which need attention. I was kinda busy for few weeks. I will look into the bugs next weekend.

Also, I have removed splitstream dependency(62fa71c) in favor of [raw_decode](https://docs.python.org/3/library/json.html#json.JSONDecoder.raw_decode).

**Comment by kronpano** [comment]
Just tried it and got it to work on Linux. Thanks for fixing that - my python knowledge is certainly not the best.
